[package]
name = "kailian"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
clap_complete = "4.5.47"
curl = "0.4.47"
ollama-rs = { version = "0.3.0", features = ["stream"] }
tokio = "1.44.1"
tokio-stream = "0.1.17"
