#Do not edit this file!!!
#Use the command 'kailian --set-environment' instead
name = laurenzwarhier 
endpoint = http://10.0.0.7:11434/api/generate
info_endpoint = http://10.0.0.7:11434/api/tags
running_model_endpoint = http://10.0.0.7:11434/api/ps
ollama_version_endpoint = http://10.0.0.7:11434/api/version
